name: clang-format
on: [push]
jobs:
  clang-format-checking:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run clang-format
      uses: HorstBaerbel/action-clang-format@1.4
