name: clang-format
on: [push]
jobs:
  clang-format-checking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: HorstBaerbel/action-clang-format@1.4
        with:
          excludedirs: 'Source/ThirdParty'
          extensions: 'c,h,C,H,cpp,hpp,cc,hh,c++,h++,cxx,hxx'
          style: 'file'
